#!/usr/bin/env bash
curl -i -X POST http://localhost:3088/mcp   \
  -H "Accept: application/json, text/event-stream" \
  -H "Content-Type: application/json"   \
  -d '{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "initialize",
    "params": {
      "protocolVersion": "2025-03-26",
      "capabilities": {},
      "clientInfo": {
        "name": "curl-test",
        "version": "1.0.0"
      }
    }
  }'
